# syntax=docker/dockerfile:1
# Fast local runtime image using host-built bootJar
ARG JVM_RUNTIME_IMAGE=eclipse-temurin:25-jre

FROM ${JVM_RUNTIME_IMAGE}
ARG APP_PROJECT
ENV APP_PROJECT=${APP_PROJECT}
WORKDIR /app
RUN useradd --system --create-home --uid 10001 squarewise
COPY "app/${APP_PROJECT}/build/libs/squarewise-${APP_PROJECT}-0.1.0-SNAPSHOT.jar" /app/app.jar
USER squarewise
EXPOSE 8080
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=65", "-jar", "/app/app.jar"]
