services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
  idp-keycloak:
    extends:
      file: docker-compose.yml
      service: idp-keycloak

volumes:
  postgres-data:
