services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.yml
      service: redis
  idp-keycloak:
    extends:
      file: docker-compose.yml
      service: idp-keycloak

volumes:
  postgres-data:
