services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
  redis:
    extends:
      file: docker-compose.yml
      service: redis
  idp-keycloak:
    extends:
      file: docker-compose.yml
      service: idp-keycloak
  mailpit:
    extends:
      file: docker-compose.yml
      service: mailpit

volumes:
  postgres-data:
