"""Build and populate the authoritative six-digit error catalog and lifecycle history.

Allocates 100% of audited call sites across Accounts, Expense Core, Notifications,
BFF, and Platform libraries. Enforces least disclosure, security hiding, and
zero runtime reflection constraints.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List
import yaml  # type: ignore[import-untyped]  # PyYAML ships without inline type stubs

from tools.errors.validate_catalog import (
    validate_catalog,
    validate_domains_registry,
    validate_six_digit_record,
)

ROOT = Path(__file__).resolve().parents[2]

ENTRIES: List[Dict[str, Any]] = [
    # ==========================================
    # DOMAIN 1: ACCOUNTS (11-15)
    # ==========================================
    # Module 11: Profile
    {
        "numericCode": "111101",
        "errorName": "PROFILE_REQUEST_INVALID",
        "legacyCode": "ERR-02",
        "domain": 1,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Invalid profile request",
        "safeDetail": "The provided profile parameters are invalid.",
        "messageKey": "error.profile.request_invalid",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "profile",
        "operation": "update-profile",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "111102",
        "errorName": "TIMEZONE_INVALID",
        "legacyCode": "ERR-02",
        "domain": 1,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 2,
        "title": "Invalid timezone",
        "safeDetail": "The specified timezone identifier is not recognized.",
        "messageKey": "error.profile.timezone_invalid",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "profile",
        "operation": "update-preferences",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "117101",
        "errorName": "PROFILE_SUBJECT_INVALID",
        "legacyCode": "ERR-03",
        "domain": 1,
        "module": 1,
        "layer": 7,
        "category": 1,
        "sequence": 1,
        "title": "Invalid authenticated subject",
        "safeDetail": "The authenticated subject is missing or malformed.",
        "messageKey": "error.profile.subject_invalid",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "profile",
        "operation": "get-profile",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 401,
        "graphqlClassification": "UNAUTHENTICATED",
        "retryPolicy": "REAUTHENTICATE",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/authentication",
    },
    {
        "numericCode": "117201",
        "errorName": "AUTHENTICATED_PROFILE_NOT_FOUND",
        "legacyCode": "ERR-03",
        "domain": 1,
        "module": 1,
        "layer": 7,
        "category": 2,
        "sequence": 1,
        "title": "Profile not found",
        "safeDetail": "The profile associated with the authenticated subject was not found.",
        "messageKey": "error.profile.not_found",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "profile",
        "operation": "get-profile",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 401,
        "graphqlClassification": "UNAUTHENTICATED",
        "retryPolicy": "REAUTHENTICATE",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/authentication",
    },
    {
        "numericCode": "117202",
        "errorName": "FOREIGN_PROFILE_ACCESS_DENIED",
        "legacyCode": "ERR-04",
        "domain": 1,
        "module": 1,
        "layer": 7,
        "category": 2,
        "sequence": 2,
        "title": "Access denied",
        "safeDetail": "You do not have permission to view or modify this profile.",
        "messageKey": "error.profile.access_denied",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "profile",
        "operation": "get-foreign-profile",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 403,
        "graphqlClassification": "FORBIDDEN",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "117203",
        "errorName": "BATCH_LOOKUP_UNAUTHORIZED",
        "legacyCode": "ERR-04",
        "domain": 1,
        "module": 1,
        "layer": 7,
        "category": 2,
        "sequence": 3,
        "title": "Unauthorized batch lookup",
        "safeDetail": "Workload authority is required for multi-subject profile lookup.",
        "messageKey": "error.profile.batch_unauthorized",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "profile",
        "operation": "batch-lookup",
        "transports": ["REST"],
        "httpStatus": 403,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 12: Authentication
    {
        "numericCode": "127101",
        "errorName": "LOGIN_CODE_INVALID",
        "legacyCode": "ERR-03",
        "domain": 1,
        "module": 2,
        "layer": 7,
        "category": 1,
        "sequence": 1,
        "title": "Invalid login code",
        "safeDetail": "The provided authentication code is invalid or has expired.",
        "messageKey": "error.auth.login_code_invalid",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "auth",
        "operation": "verify-code",
        "transports": ["REST"],
        "httpStatus": 401,
        "retryPolicy": "REAUTHENTICATE",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/authentication",
    },
    {
        "numericCode": "127801",
        "errorName": "LOGIN_RATE_LIMITED",
        "legacyCode": "ERR-11",
        "domain": 1,
        "module": 2,
        "layer": 7,
        "category": 8,
        "sequence": 1,
        "title": "Login rate limit exceeded",
        "safeDetail": "Too many login attempts. Please retry after the indicated window.",
        "messageKey": "error.auth.login_rate_limited",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "auth",
        "operation": "start-login",
        "transports": ["REST"],
        "httpStatus": 429,
        "retryPolicy": "RETRY_AFTER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/rate-limiting",
    },
    {
        "numericCode": "127802",
        "errorName": "LOGIN_LIMITER_UNAVAILABLE",
        "legacyCode": "ERR-11",
        "domain": 1,
        "module": 2,
        "layer": 7,
        "category": 8,
        "sequence": 2,
        "title": "Rate limiter unavailable",
        "safeDetail": "Authentication rate limiter is temporarily unavailable.",
        "messageKey": "error.auth.limiter_unavailable",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "auth",
        "operation": "start-login",
        "transports": ["REST"],
        "httpStatus": 429,
        "retryPolicy": "RETRY_AFTER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/redis-limiter",
    },
    # Module 13: Session
    {
        "numericCode": "137101",
        "errorName": "REFRESH_TOKEN_INVALID",
        "legacyCode": "ERR-03",
        "domain": 1,
        "module": 3,
        "layer": 7,
        "category": 1,
        "sequence": 1,
        "title": "Invalid refresh token",
        "safeDetail": "The provided refresh token is malformed or invalid.",
        "messageKey": "error.session.refresh_token_invalid",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "session",
        "operation": "refresh-token",
        "transports": ["REST"],
        "httpStatus": 401,
        "retryPolicy": "REAUTHENTICATE",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/authentication",
    },
    {
        "numericCode": "137401",
        "errorName": "SESSION_EXPIRED",
        "legacyCode": "ERR-03",
        "domain": 1,
        "module": 3,
        "layer": 7,
        "category": 4,
        "sequence": 1,
        "title": "Session expired",
        "safeDetail": "The current session has expired. Please reauthenticate.",
        "messageKey": "error.session.expired",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "session",
        "operation": "refresh-token",
        "transports": ["REST"],
        "httpStatus": 401,
        "retryPolicy": "REAUTHENTICATE",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/authentication",
    },
    {
        "numericCode": "137402",
        "errorName": "SESSION_REVOKED",
        "legacyCode": "ERR-03",
        "domain": 1,
        "module": 3,
        "layer": 7,
        "category": 4,
        "sequence": 2,
        "title": "Session revoked",
        "safeDetail": "The session has been revoked.",
        "messageKey": "error.session.revoked",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "session",
        "operation": "refresh-token",
        "transports": ["REST"],
        "httpStatus": 401,
        "retryPolicy": "REAUTHENTICATE",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/authentication",
    },
    {
        "numericCode": "137403",
        "errorName": "REFRESH_REPLAY_DETECTED",
        "legacyCode": "ERR-03",
        "domain": 1,
        "module": 3,
        "layer": 7,
        "category": 4,
        "sequence": 3,
        "title": "Token replay detected",
        "safeDetail": "Refresh token replay detected. Session family revoked for security.",
        "messageKey": "error.session.replay_detected",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "session",
        "operation": "refresh-token",
        "transports": ["REST"],
        "httpStatus": 401,
        "retryPolicy": "REAUTHENTICATE",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/authentication",
    },
    {
        "numericCode": "137404",
        "errorName": "SESSION_SUBJECT_MISMATCH",
        "legacyCode": "ERR-03",
        "domain": 1,
        "module": 3,
        "layer": 7,
        "category": 4,
        "sequence": 4,
        "title": "Session subject mismatch",
        "safeDetail": "The session token subject does not match the requested profile.",
        "messageKey": "error.session.subject_mismatch",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "session",
        "operation": "refresh-token",
        "transports": ["REST"],
        "httpStatus": 401,
        "retryPolicy": "REAUTHENTICATE",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/authentication",
    },
    {
        "numericCode": "137801",
        "errorName": "REFRESH_RATE_LIMITED",
        "legacyCode": "ERR-11",
        "domain": 1,
        "module": 3,
        "layer": 7,
        "category": 8,
        "sequence": 1,
        "title": "Refresh rate limit exceeded",
        "safeDetail": "Too many token refresh attempts. Please retry later.",
        "messageKey": "error.session.refresh_rate_limited",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "session",
        "operation": "refresh-token",
        "transports": ["REST"],
        "httpStatus": 429,
        "retryPolicy": "RETRY_AFTER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/accounts/rate-limiting",
    },
    # Module 14: Lifecycle
    {
        "numericCode": "147401",
        "errorName": "ACCOUNT_DELETION_ALREADY_REQUESTED",
        "legacyCode": "ERR-06",
        "domain": 1,
        "module": 4,
        "layer": 7,
        "category": 4,
        "sequence": 1,
        "title": "Account deletion in progress",
        "safeDetail": "A deletion request for this account is already pending.",
        "messageKey": "error.lifecycle.deletion_pending",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "lifecycle",
        "operation": "delete-account",
        "transports": ["REST"],
        "httpStatus": 409,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "147402",
        "errorName": "ACCOUNT_EXPORT_ALREADY_PENDING",
        "legacyCode": "ERR-06",
        "domain": 1,
        "module": 4,
        "layer": 7,
        "category": 4,
        "sequence": 2,
        "title": "Account export in progress",
        "safeDetail": "A data export request for this account is already processing.",
        "messageKey": "error.lifecycle.export_pending",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "lifecycle",
        "operation": "export-account",
        "transports": ["REST"],
        "httpStatus": 409,
        "retryPolicy": "NEVER",
        "severity": "INFO",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 15: Identity
    {
        "numericCode": "157301",
        "errorName": "IDENTITY_ALREADY_LINKED",
        "legacyCode": "ERR-06",
        "domain": 1,
        "module": 5,
        "layer": 7,
        "category": 3,
        "sequence": 1,
        "title": "Identity already linked",
        "safeDetail": "This external identity is already linked to another account.",
        "messageKey": "error.identity.already_linked",
        "owner": "Accounts",
        "source": "squarewise-accounts",
        "component": "identity",
        "operation": "link-identity",
        "transports": ["REST"],
        "httpStatus": 409,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },

    # ==========================================
    # DOMAIN 2: EXPENSE CORE (21-28)
    # ==========================================
    # Module 21: Groups
    {
        "numericCode": "211101",
        "errorName": "GROUP_REQUEST_INVALID",
        "legacyCode": "ERR-02",
        "domain": 2,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Invalid group request",
        "safeDetail": "Group parameters are invalid or missing required fields.",
        "messageKey": "error.groups.request_invalid",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "groups",
        "operation": "create-group",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "213201",
        "errorName": "GROUP_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 2,
        "module": 1,
        "layer": 3,
        "category": 2,
        "sequence": 1,
        "title": "Group not found",
        "safeDetail": "The requested group does not exist.",
        "messageKey": "error.groups.not_found",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "groups",
        "operation": "get-group",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 404,
        "graphqlClassification": "NOT_FOUND",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "213301",
        "errorName": "GROUP_NAME_CONFLICT",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 1,
        "layer": 3,
        "category": 3,
        "sequence": 1,
        "title": "Group name conflict",
        "safeDetail": "A group with this name already exists in your account.",
        "messageKey": "error.groups.name_conflict",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "groups",
        "operation": "create-group",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "213401",
        "errorName": "GROUP_ARCHIVED",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 1,
        "layer": 3,
        "category": 4,
        "sequence": 1,
        "title": "Group is archived",
        "safeDetail": "Operations cannot be performed on an archived group.",
        "messageKey": "error.groups.archived",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "groups",
        "operation": "update-group",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "217201",
        "errorName": "GROUP_ACCESS_HIDDEN",
        "legacyCode": "ERR-05",
        "domain": 2,
        "module": 1,
        "layer": 7,
        "category": 2,
        "sequence": 1,
        "title": "Group not found",
        "safeDetail": "The requested group does not exist.",
        "messageKey": "error.groups.not_found",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "groups",
        "operation": "get-group",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 404,
        "graphqlClassification": "NOT_FOUND",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 22: Membership
    {
        "numericCode": "221201",
        "errorName": "INVITATION_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 2,
        "module": 2,
        "layer": 1,
        "category": 2,
        "sequence": 1,
        "title": "Invitation not found",
        "safeDetail": "The invitation token is invalid or does not exist.",
        "messageKey": "error.membership.invitation_not_found",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "membership",
        "operation": "get-invitation",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 404,
        "graphqlClassification": "NOT_FOUND",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "223201",
        "errorName": "MEMBER_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 2,
        "module": 2,
        "layer": 3,
        "category": 2,
        "sequence": 1,
        "title": "Group member not found",
        "safeDetail": "The participant is not a member of this group.",
        "messageKey": "error.membership.member_not_found",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "membership",
        "operation": "get-member",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 404,
        "graphqlClassification": "NOT_FOUND",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "223202",
        "errorName": "PLACEHOLDER_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 2,
        "module": 2,
        "layer": 3,
        "category": 2,
        "sequence": 2,
        "title": "Placeholder member not found",
        "safeDetail": "The placeholder participant was not found.",
        "messageKey": "error.membership.placeholder_not_found",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "membership",
        "operation": "claim-placeholder",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 404,
        "graphqlClassification": "NOT_FOUND",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "223401",
        "errorName": "INVITATION_EXPIRED",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 2,
        "layer": 3,
        "category": 4,
        "sequence": 1,
        "title": "Invitation expired",
        "safeDetail": "This group invitation has expired.",
        "messageKey": "error.membership.invitation_expired",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "membership",
        "operation": "accept-invitation",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "223402",
        "errorName": "INVITATION_ALREADY_CLAIMED",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 2,
        "layer": 3,
        "category": 4,
        "sequence": 2,
        "title": "Invitation already claimed",
        "safeDetail": "This invitation has already been accepted.",
        "messageKey": "error.membership.invitation_claimed",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "membership",
        "operation": "accept-invitation",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "223403",
        "errorName": "INVITATION_REVOKED",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 2,
        "layer": 3,
        "category": 4,
        "sequence": 3,
        "title": "Invitation revoked",
        "safeDetail": "This invitation has been revoked by a group administrator.",
        "messageKey": "error.membership.invitation_revoked",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "membership",
        "operation": "accept-invitation",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "223404",
        "errorName": "MEMBER_ALREADY_REMOVED",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 2,
        "layer": 3,
        "category": 4,
        "sequence": 4,
        "title": "Member already removed",
        "safeDetail": "The participant is no longer an active member of this group.",
        "messageKey": "error.membership.already_removed",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "membership",
        "operation": "remove-member",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "223405",
        "errorName": "PLACEHOLDER_ALREADY_BOUND",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 2,
        "layer": 3,
        "category": 4,
        "sequence": 5,
        "title": "Placeholder already bound",
        "safeDetail": "The placeholder participant is already bound to a user account.",
        "messageKey": "error.membership.placeholder_bound",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "membership",
        "operation": "claim-placeholder",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 23: Expenses
    {
        "numericCode": "231101",
        "errorName": "EXPENSE_REQUEST_INVALID",
        "legacyCode": "ERR-02",
        "domain": 2,
        "module": 3,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Invalid expense request",
        "safeDetail": "Expense parameters, currency, amount, or dates are invalid.",
        "messageKey": "error.expenses.request_invalid",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "expenses",
        "operation": "create-expense",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "233201",
        "errorName": "EXPENSE_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 2,
        "module": 3,
        "layer": 3,
        "category": 2,
        "sequence": 1,
        "title": "Expense not found",
        "safeDetail": "The requested expense does not exist.",
        "messageKey": "error.expenses.not_found",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "expenses",
        "operation": "get-expense",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 404,
        "graphqlClassification": "NOT_FOUND",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "233301",
        "errorName": "EXPENSE_VERSION_CONFLICT",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 3,
        "layer": 3,
        "category": 3,
        "sequence": 1,
        "title": "Expense version conflict",
        "safeDetail": "The expense was modified concurrently. Please refresh and retry.",
        "messageKey": "error.expenses.version_conflict",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "expenses",
        "operation": "update-expense",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "REFRESH",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/concurrency",
    },
    {
        "numericCode": "233302",
        "errorName": "EXPENSE_IDEMPOTENCY_CONFLICT",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 3,
        "layer": 3,
        "category": 3,
        "sequence": 2,
        "title": "Idempotency key conflict",
        "safeDetail": "An identical idempotency key was previously used with different parameters.",
        "messageKey": "error.expenses.idempotency_conflict",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "expenses",
        "operation": "create-expense",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "SAME_IDEMPOTENCY_KEY",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/idempotency",
    },
    {
        "numericCode": "233501",
        "errorName": "ALLOCATION_SUM_MISMATCH",
        "legacyCode": "ERR-02",
        "domain": 2,
        "module": 3,
        "layer": 3,
        "category": 5,
        "sequence": 1,
        "title": "Allocation sum mismatch",
        "safeDetail": "The sum of participant allocations does not match the total expense amount.",
        "messageKey": "error.expenses.allocation_sum_mismatch",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "expenses",
        "operation": "create-expense",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "233502",
        "errorName": "PARTICIPANT_SET_INVALID",
        "legacyCode": "ERR-02",
        "domain": 2,
        "module": 3,
        "layer": 3,
        "category": 5,
        "sequence": 2,
        "title": "Invalid participant set",
        "safeDetail": "Payer or split participants are not valid active members of this group.",
        "messageKey": "error.expenses.participant_set_invalid",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "expenses",
        "operation": "create-expense",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "233503",
        "errorName": "DUPLICATE_EXPENSE_REJECTED",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 3,
        "layer": 3,
        "category": 5,
        "sequence": 3,
        "title": "Duplicate expense rejected",
        "safeDetail": "A duplicate expense with identical amount, payer, and timestamp was rejected.",
        "messageKey": "error.expenses.duplicate_rejected",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "expenses",
        "operation": "create-expense",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 24: Settlements
    {
        "numericCode": "243201",
        "errorName": "SETTLEMENT_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 2,
        "module": 4,
        "layer": 3,
        "category": 2,
        "sequence": 1,
        "title": "Settlement not found",
        "safeDetail": "The requested settlement does not exist.",
        "messageKey": "error.settlements.not_found",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "settlements",
        "operation": "get-settlement",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 404,
        "graphqlClassification": "NOT_FOUND",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "243301",
        "errorName": "SETTLEMENT_VERSION_CONFLICT",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 4,
        "layer": 3,
        "category": 3,
        "sequence": 1,
        "title": "Settlement version conflict",
        "safeDetail": "The settlement was modified concurrently. Please refresh and retry.",
        "messageKey": "error.settlements.version_conflict",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "settlements",
        "operation": "update-settlement",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "REFRESH",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/settlements",
    },
    {
        "numericCode": "243401",
        "errorName": "SETTLEMENT_ALREADY_REVERSED",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 4,
        "layer": 3,
        "category": 4,
        "sequence": 1,
        "title": "Settlement already reversed",
        "safeDetail": "This settlement has already been reversed.",
        "messageKey": "error.settlements.already_reversed",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "settlements",
        "operation": "reverse-settlement",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "243501",
        "errorName": "INSUFFICIENT_BALANCE",
        "legacyCode": "ERR-10",
        "domain": 2,
        "module": 4,
        "layer": 3,
        "category": 5,
        "sequence": 1,
        "title": "Insufficient balance for settlement",
        "safeDetail": "Settlement amount exceeds the outstanding balance.",
        "messageKey": "error.settlements.insufficient_balance",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "settlements",
        "operation": "create-settlement",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 422,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 25: Recurrence
    {
        "numericCode": "253201",
        "errorName": "SCHEDULE_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 2,
        "module": 5,
        "layer": 3,
        "category": 2,
        "sequence": 1,
        "title": "Recurring schedule not found",
        "safeDetail": "The requested recurring schedule does not exist.",
        "messageKey": "error.recurrence.schedule_not_found",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "recurrence",
        "operation": "get-schedule",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 404,
        "graphqlClassification": "NOT_FOUND",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "253301",
        "errorName": "SCHEDULE_VERSION_CONFLICT",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 5,
        "layer": 3,
        "category": 3,
        "sequence": 1,
        "title": "Schedule version conflict",
        "safeDetail": "The recurring schedule was modified concurrently.",
        "messageKey": "error.recurrence.version_conflict",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "recurrence",
        "operation": "update-schedule",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "REFRESH",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/recurrence",
    },
    {
        "numericCode": "253401",
        "errorName": "SCHEDULE_PAUSED",
        "legacyCode": "ERR-06",
        "domain": 2,
        "module": 5,
        "layer": 3,
        "category": 4,
        "sequence": 1,
        "title": "Schedule is paused",
        "safeDetail": "The recurring schedule is paused and cannot trigger occurrences.",
        "messageKey": "error.recurrence.paused",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "recurrence",
        "operation": "trigger-occurrence",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "255601",
        "errorName": "OCCURRENCE_GENERATION_FAILED",
        "legacyCode": "ERR-01",
        "domain": 2,
        "module": 5,
        "layer": 5,
        "category": 6,
        "sequence": 1,
        "title": "Occurrence generation failed",
        "safeDetail": "Failed to create scheduled expense occurrence due to internal state.",
        "messageKey": "error.recurrence.occurrence_failed",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "recurrence",
        "operation": "generate-occurrence",
        "transports": ["SCHEDULED", "INTERNAL"],
        "retryPolicy": "NEVER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/recurrence",
    },
    # Module 26: Sync
    {
        "numericCode": "261101",
        "errorName": "SYNC_CURSOR_INVALID",
        "legacyCode": "ERR-02",
        "domain": 2,
        "module": 6,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Invalid sync cursor",
        "safeDetail": "The provided sync cursor is malformed or invalid.",
        "messageKey": "error.sync.cursor_invalid",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "sync",
        "operation": "sync-feed",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "261102",
        "errorName": "SYNC_CURSOR_EXPIRED",
        "legacyCode": "ERR-02",
        "domain": 2,
        "module": 6,
        "layer": 1,
        "category": 1,
        "sequence": 2,
        "title": "Sync cursor expired",
        "safeDetail": "The sync cursor has expired. Full sync is required.",
        "messageKey": "error.sync.cursor_expired",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "sync",
        "operation": "sync-feed",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "RESYNC",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/sync-conflicts",
    },
    {
        "numericCode": "263301",
        "errorName": "SYNC_REVISION_CONFLICT",
        "legacyCode": "ERR-09",
        "domain": 2,
        "module": 6,
        "layer": 3,
        "category": 3,
        "sequence": 1,
        "title": "Sync revision conflict",
        "safeDetail": "The offline change conflicts with current server revision.",
        "messageKey": "error.sync.revision_conflict",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "sync",
        "operation": "replay-change",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 409,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "RESYNC",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/sync-conflicts",
    },
    # Module 27: Search
    {
        "numericCode": "271101",
        "errorName": "SEARCH_QUERY_INVALID",
        "legacyCode": "ERR-02",
        "domain": 2,
        "module": 7,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Invalid search query",
        "safeDetail": "Search filters, sort parameters, or date ranges are invalid.",
        "messageKey": "error.search.query_invalid",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "search",
        "operation": "search-expenses",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "271102",
        "errorName": "EXPORT_REQUEST_INVALID",
        "legacyCode": "ERR-02",
        "domain": 2,
        "module": 7,
        "layer": 1,
        "category": 1,
        "sequence": 2,
        "title": "Invalid export request",
        "safeDetail": "Export row bounds or export format parameters are invalid.",
        "messageKey": "error.search.export_invalid",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "search",
        "operation": "export-csv",
        "transports": ["REST"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 28: Outbox
    {
        "numericCode": "285701",
        "errorName": "OUTBOX_RELAY_PUBLISH_FAILED",
        "legacyCode": "ERR-01",
        "domain": 2,
        "module": 8,
        "layer": 5,
        "category": 7,
        "sequence": 1,
        "title": "Outbox relay publish failed",
        "safeDetail": "Failed to publish message from transactional outbox to broker.",
        "messageKey": "error.outbox.publish_failed",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "outbox",
        "operation": "relay-outbox",
        "transports": ["MESSAGING", "SCHEDULED"],
        "retryPolicy": "RETRY_AFTER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/outbox-relay",
    },
    {
        "numericCode": "285601",
        "errorName": "OUTBOX_RECORD_CORRUPT",
        "legacyCode": "ERR-01",
        "domain": 2,
        "module": 8,
        "layer": 5,
        "category": 6,
        "sequence": 1,
        "title": "Corrupt outbox record",
        "safeDetail": "Outbox payload could not be deserialized or validated.",
        "messageKey": "error.outbox.record_corrupt",
        "owner": "Expense Core",
        "source": "squarewise-expense-core",
        "component": "outbox",
        "operation": "relay-outbox",
        "transports": ["MESSAGING", "SCHEDULED"],
        "retryPolicy": "NEVER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/expense-core/outbox-corruption",
    },

    # ==========================================
    # DOMAIN 3: NOTIFICATIONS (31-34)
    # ==========================================
    # Module 31: Inbox
    {
        "numericCode": "311101",
        "errorName": "INBOX_CURSOR_INVALID",
        "legacyCode": "ERR-02",
        "domain": 3,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Invalid inbox cursor",
        "safeDetail": "The provided inbox pagination cursor is invalid.",
        "messageKey": "error.inbox.cursor_invalid",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "inbox",
        "operation": "get-inbox",
        "transports": ["REST"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "311102",
        "errorName": "INBOX_LIMIT_OUT_OF_RANGE",
        "legacyCode": "ERR-02",
        "domain": 3,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 2,
        "title": "Inbox limit out of range",
        "safeDetail": "The requested pagination limit exceeds the allowed bound.",
        "messageKey": "error.inbox.limit_invalid",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "inbox",
        "operation": "get-inbox",
        "transports": ["REST"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "317201",
        "errorName": "INBOX_NOTIFICATION_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 3,
        "module": 1,
        "layer": 7,
        "category": 2,
        "sequence": 1,
        "title": "Notification not found",
        "safeDetail": "The requested notification does not exist.",
        "messageKey": "error.inbox.not_found",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "inbox",
        "operation": "mark-read",
        "transports": ["REST"],
        "httpStatus": 404,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "317202",
        "errorName": "INBOX_ACCESS_HIDDEN",
        "legacyCode": "ERR-05",
        "domain": 3,
        "module": 1,
        "layer": 7,
        "category": 2,
        "sequence": 2,
        "title": "Notification not found",
        "safeDetail": "The requested notification does not exist.",
        "messageKey": "error.inbox.not_found",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "inbox",
        "operation": "mark-read",
        "transports": ["REST"],
        "httpStatus": 404,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 32: Delivery
    {
        "numericCode": "325701",
        "errorName": "NOTIFICATION_DISPATCH_FAILED",
        "legacyCode": "ERR-07",
        "domain": 3,
        "module": 2,
        "layer": 5,
        "category": 7,
        "sequence": 1,
        "title": "Notification dispatch failed",
        "safeDetail": "Failed to deliver notification through the intended channel.",
        "messageKey": "error.delivery.dispatch_failed",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "delivery",
        "operation": "dispatch-notification",
        "transports": ["MESSAGING"],
        "retryPolicy": "RETRY_AFTER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/notifications/dispatch-failures",
    },
    {
        "numericCode": "325601",
        "errorName": "NOTIFICATION_PAYLOAD_CORRUPT",
        "legacyCode": "ERR-07",
        "domain": 3,
        "module": 2,
        "layer": 5,
        "category": 6,
        "sequence": 1,
        "title": "Corrupt notification payload",
        "safeDetail": "Notification event payload could not be parsed or validated.",
        "messageKey": "error.delivery.payload_corrupt",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "delivery",
        "operation": "process-event",
        "transports": ["MESSAGING"],
        "retryPolicy": "NEVER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/notifications/payload-corruption",
    },
    # Module 33: Preferences
    {
        "numericCode": "331101",
        "errorName": "NOTIFICATION_PREFERENCE_INVALID",
        "legacyCode": "ERR-02",
        "domain": 3,
        "module": 3,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Invalid notification preference",
        "safeDetail": "The specified notification channel or preference setting is invalid.",
        "messageKey": "error.preferences.invalid",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "preferences",
        "operation": "update-preferences",
        "transports": ["REST"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 34: Email
    {
        "numericCode": "341101",
        "errorName": "EMAIL_RECIPIENT_REQUIRED",
        "legacyCode": "ERR-02",
        "domain": 3,
        "module": 4,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Email recipient required",
        "safeDetail": "A valid recipient email address is required.",
        "messageKey": "error.email.recipient_required",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "email",
        "operation": "send-email",
        "transports": ["REST", "MESSAGING"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "341102",
        "errorName": "EMAIL_TEMPLATE_INPUT_INVALID",
        "legacyCode": "ERR-02",
        "domain": 3,
        "module": 4,
        "layer": 1,
        "category": 1,
        "sequence": 2,
        "title": "Invalid email template input",
        "safeDetail": "Required template parameters for email rendering are missing or invalid.",
        "messageKey": "error.email.template_invalid",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "email",
        "operation": "render-template",
        "transports": ["REST", "MESSAGING"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "345701",
        "errorName": "EMAIL_DISPATCH_FAILED",
        "legacyCode": "ERR-07",
        "domain": 3,
        "module": 4,
        "layer": 5,
        "category": 7,
        "sequence": 1,
        "title": "Email dispatch failed",
        "safeDetail": "SMTP server rejected the email dispatch or connection timed out.",
        "messageKey": "error.email.dispatch_failed",
        "owner": "Notifications",
        "source": "squarewise-notifications",
        "component": "email",
        "operation": "dispatch-email",
        "transports": ["MESSAGING"],
        "retryPolicy": "RETRY_AFTER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/notifications/smtp-delivery",
    },

    # ==========================================
    # DOMAIN 4: BFF (41-43)
    # ==========================================
    # Module 41: GraphQL
    {
        "numericCode": "411101",
        "errorName": "GRAPHQL_INPUT_INVALID",
        "legacyCode": "ERR-02",
        "domain": 4,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Invalid GraphQL input",
        "safeDetail": "The provided GraphQL query arguments are invalid.",
        "messageKey": "error.graphql.input_invalid",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "graphql",
        "operation": "resolve-query",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "411102",
        "errorName": "GRAPHQL_OPERATION_INVALID",
        "legacyCode": "ERR-02",
        "domain": 4,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 2,
        "title": "Invalid GraphQL operation",
        "safeDetail": "The requested GraphQL operation is not supported.",
        "messageKey": "error.graphql.operation_invalid",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "graphql",
        "operation": "execute-operation",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 400,
        "graphqlClassification": "BAD_REQUEST",
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "412901",
        "errorName": "GRAPHQL_AGGREGATION_FAILED",
        "legacyCode": "ERR-08",
        "domain": 4,
        "module": 1,
        "layer": 2,
        "category": 9,
        "sequence": 1,
        "title": "GraphQL aggregation failed",
        "safeDetail": "Failed to assemble response from upstream services.",
        "messageKey": "error.graphql.aggregation_failed",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "graphql",
        "operation": "aggregate-response",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 500,
        "graphqlClassification": "INTERNAL_ERROR",
        "retryPolicy": "NEVER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 42: Transport
    {
        "numericCode": "426701",
        "errorName": "UPSTREAM_PROTOCOL_INVALID",
        "legacyCode": "ERR-08",
        "domain": 4,
        "module": 2,
        "layer": 6,
        "category": 7,
        "sequence": 1,
        "title": "Invalid upstream response",
        "safeDetail": "The upstream service returned an unparseable response.",
        "messageKey": "error.upstream.protocol_invalid",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "transport",
        "operation": "call-upstream",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 502,
        "graphqlClassification": "INTERNAL_ERROR",
        "retryPolicy": "RETRY_AFTER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/bff/upstream-protocol",
    },
    {
        "numericCode": "426702",
        "errorName": "UPSTREAM_RESPONSE_DECODE_FAILED",
        "legacyCode": "ERR-08",
        "domain": 4,
        "module": 2,
        "layer": 6,
        "category": 7,
        "sequence": 2,
        "title": "Failed to decode upstream response",
        "safeDetail": "Could not decode data payload from upstream service.",
        "messageKey": "error.upstream.decode_failed",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "transport",
        "operation": "decode-upstream",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 502,
        "graphqlClassification": "INTERNAL_ERROR",
        "retryPolicy": "NEVER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "426801",
        "errorName": "UPSTREAM_TIMEOUT",
        "legacyCode": "ERR-08",
        "domain": 4,
        "module": 2,
        "layer": 6,
        "category": 8,
        "sequence": 1,
        "title": "Upstream service timeout",
        "safeDetail": "The upstream service did not respond within the configured timeout.",
        "messageKey": "error.upstream.timeout",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "transport",
        "operation": "call-upstream",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 504,
        "graphqlClassification": "INTERNAL_ERROR",
        "retryPolicy": "RETRY_AFTER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/bff/upstream-timeouts",
    },
    {
        "numericCode": "426802",
        "errorName": "UPSTREAM_UNAVAILABLE",
        "legacyCode": "ERR-08",
        "domain": 4,
        "module": 2,
        "layer": 6,
        "category": 8,
        "sequence": 2,
        "title": "Upstream service unavailable",
        "safeDetail": "The upstream service is currently unreachable or circuit is open.",
        "messageKey": "error.upstream.unavailable",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "transport",
        "operation": "call-upstream",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 503,
        "graphqlClassification": "INTERNAL_ERROR",
        "retryPolicy": "RETRY_AFTER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/bff/upstream-availability",
    },
    {
        "numericCode": "426803",
        "errorName": "UPSTREAM_TLS_FAILED",
        "legacyCode": "ERR-08",
        "domain": 4,
        "module": 2,
        "layer": 6,
        "category": 8,
        "sequence": 3,
        "title": "Upstream TLS handshake failed",
        "safeDetail": "Secure TLS connection to the upstream service could not be established.",
        "messageKey": "error.upstream.tls_failed",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "transport",
        "operation": "connect-upstream",
        "transports": ["REST", "GRAPHQL"],
        "httpStatus": 502,
        "graphqlClassification": "INTERNAL_ERROR",
        "retryPolicy": "NEVER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/bff/tls-failures",
    },
    # Module 43: Live Update
    {
        "numericCode": "437801",
        "errorName": "SUBSCRIPTION_LIMIT_EXCEEDED",
        "legacyCode": "ERR-11",
        "domain": 4,
        "module": 3,
        "layer": 7,
        "category": 8,
        "sequence": 1,
        "title": "Subscription limit exceeded",
        "safeDetail": "Maximum concurrent WebSocket subscriptions exceeded for this connection.",
        "messageKey": "error.live_update.limit_exceeded",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "live-update",
        "operation": "subscribe",
        "transports": ["REST", "GRAPHQL", "WEBSOCKET"],
        "httpStatus": 429,
        "graphqlClassification": "EXECUTION_ERROR",
        "retryPolicy": "RETRY_AFTER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/bff/subscription-limits",
    },
    {
        "numericCode": "437802",
        "errorName": "LIVE_UPDATE_UPSTREAM_UNAVAILABLE",
        "legacyCode": "ERR-08",
        "domain": 4,
        "module": 3,
        "layer": 7,
        "category": 8,
        "sequence": 2,
        "title": "Live update service unavailable",
        "safeDetail": "Subscription event stream is temporarily disconnected from upstream.",
        "messageKey": "error.live_update.unavailable",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "live-update",
        "operation": "subscribe",
        "transports": ["REST", "GRAPHQL", "WEBSOCKET"],
        "httpStatus": 503,
        "graphqlClassification": "INTERNAL_ERROR",
        "retryPolicy": "RETRY_AFTER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/bff/live-update-availability",
    },
    {
        "numericCode": "435701",
        "errorName": "LIVE_UPDATE_EVENT_INVALID",
        "legacyCode": "ERR-08",
        "domain": 4,
        "module": 3,
        "layer": 5,
        "category": 7,
        "sequence": 1,
        "title": "Invalid live update event",
        "safeDetail": "The received live update event could not be processed for subscribers.",
        "messageKey": "error.live_update.event_invalid",
        "owner": "BFF",
        "source": "squarewise-bff",
        "component": "live-update",
        "operation": "fanout-event",
        "transports": ["REST", "GRAPHQL", "WEBSOCKET"],
        "httpStatus": 500,
        "graphqlClassification": "INTERNAL_ERROR",
        "retryPolicy": "NEVER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },

    # ==========================================
    # DOMAIN 9: PLATFORM (91-96)
    # ==========================================
    # Module 91: Error Framework
    {
        "numericCode": "911101",
        "errorName": "REQUEST_VALIDATION_FAILED",
        "legacyCode": "ERR-02",
        "domain": 9,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 1,
        "title": "Validation failed",
        "safeDetail": "One or more request parameters failed validation.",
        "messageKey": "error.platform.validation_failed",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "handle-validation",
        "transports": ["REST"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "911102",
        "errorName": "REQUEST_BODY_MALFORMED",
        "legacyCode": "ERR-02",
        "domain": 9,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 2,
        "title": "Malformed request body",
        "safeDetail": "Request payload is not valid JSON or cannot be deserialized.",
        "messageKey": "error.platform.body_malformed",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "parse-request",
        "transports": ["REST"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "911103",
        "errorName": "REQUEST_VALUE_INVALID",
        "legacyCode": "ERR-02",
        "domain": 9,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 3,
        "title": "Invalid request parameter",
        "safeDetail": "A request parameter value is of incorrect type or format.",
        "messageKey": "error.platform.parameter_invalid",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "bind-parameter",
        "transports": ["REST"],
        "httpStatus": 400,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "911104",
        "errorName": "REQUEST_BODY_TOO_LARGE",
        "legacyCode": "ERR-02",
        "domain": 9,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 4,
        "title": "Request payload too large",
        "safeDetail": "The request body exceeds the maximum permitted size limit.",
        "messageKey": "error.platform.payload_too_large",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "read-body",
        "transports": ["REST"],
        "httpStatus": 413,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "911105",
        "errorName": "MEDIA_TYPE_UNSUPPORTED",
        "legacyCode": "ERR-02",
        "domain": 9,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 5,
        "title": "Unsupported media type",
        "safeDetail": "The Content-Type header is missing or not supported for this endpoint.",
        "messageKey": "error.platform.unsupported_media_type",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "negotiate-media-type",
        "transports": ["REST"],
        "httpStatus": 415,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "911106",
        "errorName": "METHOD_NOT_ALLOWED",
        "legacyCode": "ERR-02",
        "domain": 9,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 6,
        "title": "Method not allowed",
        "safeDetail": "The requested HTTP method is not allowed on this resource.",
        "messageKey": "error.platform.method_not_allowed",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "route-request",
        "transports": ["REST"],
        "httpStatus": 405,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "911107",
        "errorName": "REPRESENTATION_NOT_ACCEPTABLE",
        "legacyCode": "ERR-02",
        "domain": 9,
        "module": 1,
        "layer": 1,
        "category": 1,
        "sequence": 7,
        "title": "Not acceptable",
        "safeDetail": "The Accept header cannot be satisfied with available media representations.",
        "messageKey": "error.platform.not_acceptable",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "negotiate-accept",
        "transports": ["REST"],
        "httpStatus": 406,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "919201",
        "errorName": "RESOURCE_NOT_FOUND",
        "legacyCode": "ERR-05",
        "domain": 9,
        "module": 1,
        "layer": 9,
        "category": 2,
        "sequence": 1,
        "title": "Resource not found",
        "safeDetail": "The requested API resource or route does not exist.",
        "messageKey": "error.platform.not_found",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "route-request",
        "transports": ["REST"],
        "httpStatus": 404,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "919301",
        "errorName": "RESOURCE_CONFLICT",
        "legacyCode": "ERR-06",
        "domain": 9,
        "module": 1,
        "layer": 9,
        "category": 3,
        "sequence": 1,
        "title": "Resource conflict",
        "safeDetail": "The requested operation conflicts with the current resource state.",
        "messageKey": "error.platform.conflict",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "handle-conflict",
        "transports": ["REST"],
        "httpStatus": 409,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "919901",
        "errorName": "UNEXPECTED_INTERNAL_ERROR",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 1,
        "layer": 9,
        "category": 9,
        "sequence": 1,
        "title": "Internal server error",
        "safeDetail": "An unexpected error occurred while processing the request.",
        "messageKey": "error.platform.unexpected_internal",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "handle-unexpected",
        "transports": ["REST", "INTERNAL"],
        "httpStatus": 500,
        "retryPolicy": "NEVER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/unexpected-internal-errors",
    },
    {
        "numericCode": "919902",
        "errorName": "RESPONSE_SERIALIZATION_FAILED",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 1,
        "layer": 9,
        "category": 9,
        "sequence": 2,
        "title": "Response serialization failed",
        "safeDetail": "Could not format the response payload for transmission.",
        "messageKey": "error.platform.serialization_failed",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "errors",
        "operation": "serialize-response",
        "transports": ["REST", "INTERNAL"],
        "httpStatus": 500,
        "retryPolicy": "NEVER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 92: Security
    {
        "numericCode": "927101",
        "errorName": "AUTHENTICATION_REQUIRED",
        "legacyCode": "ERR-03",
        "domain": 9,
        "module": 2,
        "layer": 7,
        "category": 1,
        "sequence": 1,
        "title": "Authentication required",
        "safeDetail": "Missing, invalid, or expired credentials.",
        "messageKey": "error.platform.authentication_required",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "security",
        "operation": "authenticate",
        "transports": ["REST"],
        "httpStatus": 401,
        "retryPolicy": "REAUTHENTICATE",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/authentication",
    },
    {
        "numericCode": "927501",
        "errorName": "ACCESS_DENIED",
        "legacyCode": "ERR-04",
        "domain": 9,
        "module": 2,
        "layer": 7,
        "category": 5,
        "sequence": 1,
        "title": "Access denied",
        "safeDetail": "The authenticated caller does not have permission to perform this action.",
        "messageKey": "error.platform.access_denied",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "security",
        "operation": "authorize",
        "transports": ["REST"],
        "httpStatus": 403,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "927502",
        "errorName": "CSRF_REJECTED",
        "legacyCode": "ERR-04",
        "domain": 9,
        "module": 2,
        "layer": 7,
        "category": 5,
        "sequence": 2,
        "title": "CSRF token rejected",
        "safeDetail": "Missing or invalid Cross-Site Request Forgery validation token.",
        "messageKey": "error.platform.csrf_rejected",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "security",
        "operation": "validate-csrf",
        "transports": ["REST"],
        "httpStatus": 403,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "927503",
        "errorName": "ORIGIN_REJECTED",
        "legacyCode": "ERR-04",
        "domain": 9,
        "module": 2,
        "layer": 7,
        "category": 5,
        "sequence": 3,
        "title": "Origin rejected",
        "safeDetail": "The request Origin header is not allowed by security policy.",
        "messageKey": "error.platform.origin_rejected",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "security",
        "operation": "validate-origin",
        "transports": ["REST"],
        "httpStatus": 403,
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "927801",
        "errorName": "SECURITY_RATE_LIMITED",
        "legacyCode": "ERR-11",
        "domain": 9,
        "module": 2,
        "layer": 7,
        "category": 8,
        "sequence": 1,
        "title": "Security rate limit exceeded",
        "safeDetail": "Too many requests to protected endpoint. Access temporarily throttled.",
        "messageKey": "error.platform.rate_limited",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "security",
        "operation": "rate-limit",
        "transports": ["REST"],
        "httpStatus": 429,
        "retryPolicy": "RETRY_AFTER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/security-rate-limiting",
    },
    # Module 93: Persistence
    {
        "numericCode": "934801",
        "errorName": "DATABASE_UNAVAILABLE",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 3,
        "layer": 4,
        "category": 8,
        "sequence": 1,
        "title": "Database service unavailable",
        "safeDetail": "The persistence layer is temporarily unavailable or pool is exhausted.",
        "messageKey": "error.platform.database_unavailable",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "persistence",
        "operation": "acquire-connection",
        "transports": ["REST", "INTERNAL"],
        "httpStatus": 503,
        "retryPolicy": "RETRY_AFTER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/database-availability",
    },
    {
        "numericCode": "934802",
        "errorName": "DATABASE_OPERATION_TIMEOUT",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 3,
        "layer": 4,
        "category": 8,
        "sequence": 2,
        "title": "Database operation timeout",
        "safeDetail": "Database query timed out before completing.",
        "messageKey": "error.platform.database_timeout",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "persistence",
        "operation": "execute-query",
        "transports": ["REST", "INTERNAL"],
        "httpStatus": 503,
        "retryPolicy": "RETRY_AFTER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/database-timeouts",
    },
    {
        "numericCode": "934601",
        "errorName": "DATABASE_DATA_INCONSISTENT",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 3,
        "layer": 4,
        "category": 6,
        "sequence": 1,
        "title": "Database integrity violation",
        "safeDetail": "A data integrity violation or unexpected constraint failure occurred.",
        "messageKey": "error.platform.database_integrity",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "persistence",
        "operation": "persist-entity",
        "transports": ["REST", "INTERNAL"],
        "httpStatus": 500,
        "retryPolicy": "NEVER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/database-integrity",
    },
    # Module 94: Messaging
    {
        "numericCode": "945701",
        "errorName": "MESSAGE_PUBLISH_FAILED",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 4,
        "layer": 5,
        "category": 7,
        "sequence": 1,
        "title": "Message publish failed",
        "safeDetail": "Broker returned nack or message publish timed out.",
        "messageKey": "error.platform.message_publish_failed",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "messaging",
        "operation": "publish-event",
        "transports": ["MESSAGING"],
        "retryPolicy": "RETRY_AFTER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/message-publishing",
    },
    {
        "numericCode": "945801",
        "errorName": "BROKER_UNAVAILABLE",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 4,
        "layer": 5,
        "category": 8,
        "sequence": 1,
        "title": "Message broker unavailable",
        "safeDetail": "RabbitMQ broker connection cannot be established or is refused.",
        "messageKey": "error.platform.broker_unavailable",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "messaging",
        "operation": "connect-broker",
        "transports": ["MESSAGING"],
        "retryPolicy": "RETRY_AFTER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/broker-availability",
    },
    {
        "numericCode": "945702",
        "errorName": "MESSAGE_ENVELOPE_INVALID",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 4,
        "layer": 5,
        "category": 7,
        "sequence": 2,
        "title": "Invalid message envelope",
        "safeDetail": "Message envelope is missing required metadata or has an unknown schema version.",
        "messageKey": "error.platform.envelope_invalid",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "messaging",
        "operation": "parse-envelope",
        "transports": ["MESSAGING"],
        "retryPolicy": "NEVER",
        "severity": "ERROR",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    {
        "numericCode": "948901",
        "errorName": "PLATFORM_CONFIGURATION_INVALID",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 4,
        "layer": 8,
        "category": 9,
        "sequence": 1,
        "title": "Invalid platform configuration",
        "safeDetail": "Application startup halted due to missing or invalid required configuration.",
        "messageKey": "error.platform.config_invalid",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "messaging",
        "operation": "startup-config",
        "transports": ["STARTUP"],
        "retryPolicy": "NEVER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/startup-configuration",
    },
    # Module 95: Observability
    {
        "numericCode": "958901",
        "errorName": "OBSERVABILITY_PIPELINE_FAILED",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 5,
        "layer": 8,
        "category": 9,
        "sequence": 1,
        "title": "Observability pipeline degraded",
        "safeDetail": "Metrics or tracing export encountered a non-fatal failure.",
        "messageKey": "error.platform.observability_failed",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "observability",
        "operation": "export-telemetry",
        "transports": ["INTERNAL"],
        "retryPolicy": "NEVER",
        "severity": "WARNING",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": None,
    },
    # Module 96: IDs
    {
        "numericCode": "968901",
        "errorName": "IDENTIFIER_GENERATION_FAILED",
        "legacyCode": "ERR-01",
        "domain": 9,
        "module": 6,
        "layer": 8,
        "category": 9,
        "sequence": 1,
        "title": "Identifier generation failed",
        "safeDetail": "Secure random source or UUID generator encountered an internal failure.",
        "messageKey": "error.platform.id_generation_failed",
        "owner": "Platform",
        "source": "squarewise-platform",
        "component": "ids",
        "operation": "generate-id",
        "transports": ["REST", "INTERNAL"],
        "httpStatus": 500,
        "retryPolicy": "NEVER",
        "severity": "CRITICAL",
        "introducedIn": "1.0.0",
        "deprecatedIn": None,
        "retiredIn": None,
        "replacedBy": None,
        "runbook": "https://runbooks.squarewise.internal/platform/id-generation",
    },
]

LIFECYCLE_HISTORY: List[Dict[str, Any]] = [
    {
        "code": "ERR-12",
        "errorName": "GOVERNANCE_CHECK_SUCCESS",
        "status": "RETIRED",
        "introducedIn": "1.0.0",
        "deprecatedIn": "2.0.0",
        "retiredIn": "2.0.0",
        "sunsetDate": "2026-10-07",
        "replacedBy": None,
        "rationale": "ERR-12 was a governance verification marker returning HTTP 200, not an actual error. Formally retired without replacement under the six-digit error-code standard.",
        "migrationGuidance": "Remove dependencies on ERR-12. Health and governance endpoints return standard HTTP 200 responses without error problem documents.",
    }
]


def main() -> None:
    """Build and write catalog and lifecycle history files."""
    domains_path = ROOT / "contracts/errors/domains.yaml"
    domains_data = validate_domains_registry(domains_path)

    # Validate each entry prior to writing
    for idx, entry in enumerate(ENTRIES):
        errors = validate_six_digit_record(entry, domains_data)
        if errors:
            raise ValueError(f"Entry #{idx} ({entry.get('numericCode')}) invalid: {errors}")

    catalog_path = ROOT / "contracts/errors/error-catalog.yaml"
    catalog_content = yaml.dump(
        ENTRIES,
        sort_keys=False,
        allow_unicode=True,
    )
    header = (
        "# Authoritative Squarewise Six-Digit Error Catalog\n"
        "# Frozen and allocated under ERRC-04. Zero runtime reflection allowed.\n"
        "# Canonical format: DMLCEE (Domain, Module, Layer, Category, Sequence).\n\n"
    )
    catalog_path.write_text(header + catalog_content, encoding="utf-8")
    print(f"Wrote {len(ENTRIES)} error codes to {catalog_path.relative_to(ROOT)}")

    lifecycle_path = ROOT / "contracts/errors/lifecycle-history.yaml"
    history_content = yaml.dump(
        LIFECYCLE_HISTORY,
        sort_keys=False,
        allow_unicode=True,
    )
    lifecycle_header = (
        "# Authoritative Squarewise Error Lifecycle History\n"
        "# Tracks deprecations, retirements, and migration sunset policies.\n\n"
    )
    lifecycle_path.write_text(lifecycle_header + history_content, encoding="utf-8")
    print(f"Wrote {len(LIFECYCLE_HISTORY)} lifecycle records to {lifecycle_path.relative_to(ROOT)}")

    # Verify catalog
    count, catalog_errors = validate_catalog(catalog_path, domains_data)
    if catalog_errors:
        raise ValueError(f"Catalog validation failed: {catalog_errors}")
    print(f"Successfully verified catalog: {count} unique codes.")


if __name__ == "__main__":
    main()
