package com.subhrodip.squarewise.errors.catalog

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/** Verifies that generated definitions preserve every authoritative identity field. */
class CatalogParityTest {
    @Test
    fun `compiled catalogs match authoritative identities`() {
        val expected = listOf(
            Expected("111101", "PROFILE_REQUEST_INVALID", "Invalid profile request", 400),
            Expected("111102", "TIMEZONE_INVALID", "Invalid timezone", 400),
            Expected("117101", "PROFILE_SUBJECT_INVALID", "Invalid authenticated subject", 401),
            Expected("117201", "AUTHENTICATED_PROFILE_NOT_FOUND", "Profile not found", 404),
            Expected("117202", "FOREIGN_PROFILE_ACCESS_DENIED", "Access denied", 403),
            Expected("117203", "BATCH_LOOKUP_UNAUTHORIZED", "Unauthorized batch lookup", 403),
            Expected("127101", "LOGIN_CODE_INVALID", "Invalid login code", 401),
            Expected("127801", "LOGIN_RATE_LIMITED", "Login rate limit exceeded", 429),
            Expected("127802", "LOGIN_LIMITER_UNAVAILABLE", "Rate limiter unavailable", 429),
            Expected("137101", "REFRESH_TOKEN_INVALID", "Invalid refresh token", 401),
            Expected("137401", "SESSION_EXPIRED", "Session expired", 401),
            Expected("137402", "SESSION_REVOKED", "Session revoked", 401),
            Expected("137403", "REFRESH_REPLAY_DETECTED", "Token replay detected", 401),
            Expected("137404", "SESSION_SUBJECT_MISMATCH", "Session subject mismatch", 401),
            Expected("137801", "REFRESH_RATE_LIMITED", "Refresh rate limit exceeded", 429),
            Expected("147401", "ACCOUNT_DELETION_ALREADY_REQUESTED", "Account deletion in progress", 409),
            Expected("147402", "ACCOUNT_EXPORT_ALREADY_PENDING", "Account export in progress", 409),
            Expected("157301", "IDENTITY_ALREADY_LINKED", "Identity already linked", 409),
            Expected("211101", "GROUP_REQUEST_INVALID", "Invalid group request", 400),
            Expected("213201", "GROUP_NOT_FOUND", "Group not found", 404),
            Expected("213301", "GROUP_NAME_CONFLICT", "Group name conflict", 409),
            Expected("213401", "GROUP_ARCHIVED", "Group is archived", 409),
            Expected("217201", "GROUP_ACCESS_HIDDEN", "Group not found", 404),
            Expected("221201", "INVITATION_NOT_FOUND", "Invitation not found", 404),
            Expected("223201", "MEMBER_NOT_FOUND", "Group member not found", 404),
            Expected("223202", "PLACEHOLDER_NOT_FOUND", "Placeholder member not found", 404),
            Expected("223401", "INVITATION_EXPIRED", "Invitation expired", 409),
            Expected("223402", "INVITATION_ALREADY_CLAIMED", "Invitation already claimed", 409),
            Expected("223403", "INVITATION_REVOKED", "Invitation revoked", 409),
            Expected("223404", "MEMBER_ALREADY_REMOVED", "Member already removed", 409),
            Expected("223405", "PLACEHOLDER_ALREADY_BOUND", "Placeholder already bound", 409),
            Expected("231101", "EXPENSE_REQUEST_INVALID", "Invalid expense request", 400),
            Expected("233201", "EXPENSE_NOT_FOUND", "Expense not found", 404),
            Expected("233301", "EXPENSE_VERSION_CONFLICT", "Expense version conflict", 409),
            Expected("233302", "EXPENSE_IDEMPOTENCY_CONFLICT", "Idempotency key conflict", 409),
            Expected("233501", "ALLOCATION_SUM_MISMATCH", "Allocation sum mismatch", 400),
            Expected("233502", "PARTICIPANT_SET_INVALID", "Invalid participant set", 400),
            Expected("233503", "DUPLICATE_EXPENSE_REJECTED", "Duplicate expense rejected", 409),
            Expected("243201", "SETTLEMENT_NOT_FOUND", "Settlement not found", 404),
            Expected("243301", "SETTLEMENT_VERSION_CONFLICT", "Settlement version conflict", 409),
            Expected("243401", "SETTLEMENT_ALREADY_REVERSED", "Settlement already reversed", 409),
            Expected("243501", "INSUFFICIENT_BALANCE", "Insufficient balance for settlement", 422),
            Expected("253201", "SCHEDULE_NOT_FOUND", "Recurring schedule not found", 404),
            Expected("253301", "SCHEDULE_VERSION_CONFLICT", "Schedule version conflict", 409),
            Expected("253401", "SCHEDULE_PAUSED", "Schedule is paused", 409),
            Expected("255601", "OCCURRENCE_GENERATION_FAILED", "Occurrence generation failed", null),
            Expected("261101", "SYNC_CURSOR_INVALID", "Invalid sync cursor", 400),
            Expected("261102", "SYNC_CURSOR_EXPIRED", "Sync cursor expired", 400),
            Expected("263301", "SYNC_REVISION_CONFLICT", "Sync revision conflict", 409),
            Expected("271101", "SEARCH_QUERY_INVALID", "Invalid search query", 400),
            Expected("271102", "EXPORT_REQUEST_INVALID", "Invalid export request", 400),
            Expected("285701", "OUTBOX_RELAY_PUBLISH_FAILED", "Outbox relay publish failed", null),
            Expected("285601", "OUTBOX_RECORD_CORRUPT", "Corrupt outbox record", null),
            Expected("311101", "INBOX_CURSOR_INVALID", "Invalid inbox cursor", 400),
            Expected("311102", "INBOX_LIMIT_OUT_OF_RANGE", "Inbox limit out of range", 400),
            Expected("317201", "INBOX_NOTIFICATION_NOT_FOUND", "Notification not found", 404),
            Expected("317202", "INBOX_ACCESS_HIDDEN", "Notification not found", 404),
            Expected("325701", "NOTIFICATION_DISPATCH_FAILED", "Notification dispatch failed", null),
            Expected("325601", "NOTIFICATION_PAYLOAD_CORRUPT", "Corrupt notification payload", null),
            Expected("331101", "NOTIFICATION_PREFERENCE_INVALID", "Invalid notification preference", 400),
            Expected("341101", "EMAIL_RECIPIENT_REQUIRED", "Email recipient required", 400),
            Expected("341102", "EMAIL_TEMPLATE_INPUT_INVALID", "Invalid email template input", 400),
            Expected("345701", "EMAIL_DISPATCH_FAILED", "Email dispatch failed", null),
            Expected("411101", "GRAPHQL_INPUT_INVALID", "Invalid GraphQL input", 400),
            Expected("411102", "GRAPHQL_OPERATION_INVALID", "Invalid GraphQL operation", 400),
            Expected("412901", "GRAPHQL_AGGREGATION_FAILED", "GraphQL aggregation failed", 500),
            Expected("426701", "UPSTREAM_PROTOCOL_INVALID", "Invalid upstream response", 502),
            Expected("426702", "UPSTREAM_RESPONSE_DECODE_FAILED", "Failed to decode upstream response", 502),
            Expected("426801", "UPSTREAM_TIMEOUT", "Upstream service timeout", 504),
            Expected("426802", "UPSTREAM_UNAVAILABLE", "Upstream service unavailable", 503),
            Expected("426803", "UPSTREAM_TLS_FAILED", "Upstream TLS handshake failed", 502),
            Expected("437801", "SUBSCRIPTION_LIMIT_EXCEEDED", "Subscription limit exceeded", 429),
            Expected("437802", "LIVE_UPDATE_UPSTREAM_UNAVAILABLE", "Live update service unavailable", 503),
            Expected("435701", "LIVE_UPDATE_EVENT_INVALID", "Invalid live update event", 500),
            Expected("911101", "REQUEST_VALIDATION_FAILED", "Validation failed", 400),
            Expected("911102", "REQUEST_BODY_MALFORMED", "Malformed request body", 400),
            Expected("911103", "REQUEST_VALUE_INVALID", "Invalid request parameter", 400),
            Expected("911104", "REQUEST_BODY_TOO_LARGE", "Request payload too large", 413),
            Expected("911105", "MEDIA_TYPE_UNSUPPORTED", "Unsupported media type", 415),
            Expected("911106", "METHOD_NOT_ALLOWED", "Method not allowed", 405),
            Expected("911107", "REPRESENTATION_NOT_ACCEPTABLE", "Not acceptable", 406),
            Expected("919201", "RESOURCE_NOT_FOUND", "Resource not found", 404),
            Expected("919301", "RESOURCE_CONFLICT", "Resource conflict", 409),
            Expected("919901", "UNEXPECTED_INTERNAL_ERROR", "Internal server error", 500),
            Expected("919902", "RESPONSE_SERIALIZATION_FAILED", "Response serialization failed", 500),
            Expected("927101", "AUTHENTICATION_REQUIRED", "Authentication required", 401),
            Expected("927501", "ACCESS_DENIED", "Access denied", 403),
            Expected("927502", "CSRF_REJECTED", "CSRF token rejected", 403),
            Expected("927503", "ORIGIN_REJECTED", "Origin rejected", 403),
            Expected("927801", "SECURITY_RATE_LIMITED", "Security rate limit exceeded", 429),
            Expected("934801", "DATABASE_UNAVAILABLE", "Database service unavailable", 503),
            Expected("934802", "DATABASE_OPERATION_TIMEOUT", "Database operation timeout", 503),
            Expected("934601", "DATABASE_DATA_INCONSISTENT", "Database integrity violation", 500),
            Expected("945701", "MESSAGE_PUBLISH_FAILED", "Message publish failed", null),
            Expected("945801", "BROKER_UNAVAILABLE", "Message broker unavailable", null),
            Expected("945702", "MESSAGE_ENVELOPE_INVALID", "Invalid message envelope", null),
            Expected("948901", "PLATFORM_CONFIGURATION_INVALID", "Invalid platform configuration", null),
            Expected("958901", "OBSERVABILITY_PIPELINE_FAILED", "Observability pipeline degraded", null),
            Expected("968901", "IDENTIFIER_GENERATION_FAILED", "Identifier generation failed", 500),
        )
        assertEquals(expected.size, ErrorCatalog.all.size)
        expected.zip(ErrorCatalog.all).forEach { (record, actual) ->
            assertEquals(record.numericCode, actual.numericCode.value)
            assertEquals(record.errorName, actual.errorName)
            assertEquals(record.title, actual.title)
            assertEquals(record.httpStatus, actual.httpStatus)
        }
    }

    private data class Expected(val numericCode: String, val errorName: String, val title: String, val httpStatus: Int?)
}
